/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_logousuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Box_usuario = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        BOX_pass = new javax.swing.JPasswordField();
        Box_Olvido = new javax.swing.JCheckBox();
        Bonton_inicio = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPane_2 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel_LOGO = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel_orginal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel_logousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_01/usuario (5).png"))); // NOI18N
        Panel_login.add(jLabel_logousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 130));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de usuario");
        Panel_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Box_usuario.setBackground(new java.awt.Color(102, 102, 102));
        Box_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Box_usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        Box_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_usuarioActionPerformed(evt);
            }
        });
        Panel_login.add(Box_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 20));

        jLabel_Contraseña.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Contraseña");
        Panel_login.add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        BOX_pass.setBackground(new java.awt.Color(102, 102, 102));
        BOX_pass.setText("jPasswordField1");
        BOX_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        Panel_login.add(BOX_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 20));

        Box_Olvido.setBackground(new java.awt.Color(102, 102, 102));
        Box_Olvido.setForeground(new java.awt.Color(255, 255, 255));
        Box_Olvido.setText("¿Olvido su contraseña?");
        Panel_login.add(Box_Olvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, -1));

        Bonton_inicio.setBackground(new java.awt.Color(102, 102, 102));
        Bonton_inicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bonton_inicio.setForeground(new java.awt.Color(255, 255, 255));
        Bonton_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/iniciar-sesion (1).png"))); // NOI18N
        Bonton_inicio.setText("Iniciar sesion ");
        Bonton_inicio.setBorder(null);
        Bonton_inicio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/iniciar-sesion (1).png"))); // NOI18N
        Bonton_inicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/iniciar-sesion (3).png"))); // NOI18N
        Bonton_inicio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bonton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bonton_inicioActionPerformed(evt);
            }
        });
        Panel_login.add(Bonton_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 130, 30));

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/registrado (4).png"))); // NOI18N
        jToggleButton1.setText("Registrase");
        jToggleButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jToggleButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/registrado (4).png"))); // NOI18N
        jToggleButton1.setRolloverEnabled(true);
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/registrado (5).png"))); // NOI18N
        Panel_login.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 130, 29));

        jPane_2.setBackground(new java.awt.Color(255, 255, 0));
        jPane_2.setBorder(new javax.swing.border.MatteBorder(null));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook.png"))); // NOI18N
        jToggleButton2.setActionCommand("");
        jToggleButton2.setBorder(null);
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook.png"))); // NOI18N
        jToggleButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook (2).png"))); // NOI18N

        jLabel_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_longin/Captura de pantalla (576).png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/instagram (1).png"))); // NOI18N
        jToggleButton3.setToolTipText("");
        jToggleButton3.setBorder(null);
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook.png"))); // NOI18N
        jToggleButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/instagram (3).png"))); // NOI18N

        javax.swing.GroupLayout jPane_2Layout = new javax.swing.GroupLayout(jPane_2);
        jPane_2.setLayout(jPane_2Layout);
        jPane_2Layout.setHorizontalGroup(
            jPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane_2Layout.createSequentialGroup()
                .addGroup(jPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPane_2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPane_2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_LOGO)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPane_2Layout.setVerticalGroup(
            jPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPane_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addGroup(jPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Panel_login.add(jPane_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 180, 530));

        jLabel_orginal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_longin/fondo6.jpg"))); // NOI18N
        jLabel_orginal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        Panel_login.add(jLabel_orginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Box_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_usuarioActionPerformed

    private void Bonton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bonton_inicioActionPerformed
       
    }//GEN-LAST:event_Bonton_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField BOX_pass;
    private javax.swing.JToggleButton Bonton_inicio;
    private javax.swing.JCheckBox Box_Olvido;
    private javax.swing.JTextField Box_usuario;
    private javax.swing.JPanel Panel_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_LOGO;
    private javax.swing.JLabel jLabel_logousuario;
    private javax.swing.JLabel jLabel_orginal;
    private javax.swing.JPanel jPane_2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
