/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Registro_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Usuario
     */
    public Registro_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_1 = new javax.swing.JPanel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jText_nombre = new javax.swing.JTextField();
        jLabe_correo = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jLabel_Celular = new javax.swing.JLabel();
        jText_celular = new javax.swing.JTextField();
        jLabe_nacimineto = new javax.swing.JLabel();
        jTextnacimiento = new javax.swing.JTextField();
        jLabel_contraseña = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3_logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/agregar-usuario.png"))); // NOI18N
        jPanel_1.add(jLabel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre de usuario");
        jLabel_Nombre.setToolTipText("");
        jPanel_1.add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jText_nombre.setBackground(new java.awt.Color(102, 102, 102));
        jText_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jText_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jText_nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jPanel_1.add(jText_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, 20));

        jLabe_correo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabe_correo.setForeground(new java.awt.Color(255, 255, 255));
        jLabe_correo.setText("Correo");
        jPanel_1.add(jLabe_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTextField_correo.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_correo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField_correo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_correo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jPanel_1.add(jTextField_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 20));

        jLabel_Celular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Celular.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Celular.setText("Celular");
        jPanel_1.add(jLabel_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jText_celular.setBackground(new java.awt.Color(102, 102, 102));
        jText_celular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jText_celular.setForeground(new java.awt.Color(255, 255, 255));
        jText_celular.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jPanel_1.add(jText_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 20));

        jLabe_nacimineto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabe_nacimineto.setForeground(new java.awt.Color(255, 255, 255));
        jLabe_nacimineto.setText("Fecha de naciminento ");
        jPanel_1.add(jLabe_nacimineto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTextnacimiento.setBackground(new java.awt.Color(102, 102, 102));
        jTextnacimiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextnacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jTextnacimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jPanel_1.add(jTextnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 20));

        jLabel_contraseña.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contraseña.setText("Contraseña");
        jPanel_1.add(jLabel_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jPassword.setBackground(new java.awt.Color(102, 102, 102));
        jPassword.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jPassword.setText("jPasswordField1");
        jPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jPanel_1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 20));

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/cheque.png"))); // NOI18N
        jToggleButton1.setText("Crear cuenta");
        jToggleButton1.setBorder(null);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToggleButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/cheque.png"))); // NOI18N
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/cheque (1).png"))); // NOI18N
        jToggleButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel_1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 130, 30));

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("¿Desea guardar sus datos?");
        jPanel_1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_longin/Captura de pantalla (576).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3_logoLayout = new javax.swing.GroupLayout(jPanel3_logo);
        jPanel3_logo.setLayout(jPanel3_logoLayout);
        jPanel3_logoLayout.setHorizontalGroup(
            jPanel3_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3_logoLayout.setVerticalGroup(
            jPanel3_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jToggleButton2.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook.png"))); // NOI18N
        jToggleButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/facebook (2).png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/instagram (1).png"))); // NOI18N
        jToggleButton3.setBorder(null);
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/instagram (1).png"))); // NOI18N
        jToggleButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_fondo/instagram (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel3_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 170, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabe_correo;
    private javax.swing.JLabel jLabe_nacimineto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Celular;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3_logo;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jText_celular;
    private javax.swing.JTextField jText_nombre;
    private javax.swing.JTextField jTextnacimiento;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
